export const INITIAL_ACTION_ITEMS = [
  {
    id: 1,
    actionId: "ACT-001",
    actionItem: "Add 50 sourced candidates for CSR role before Friday.",
    roleAccount: "CSR - SIBS Operations",
    roleTitle: "Customer Service Representative",
    account: "SIBS Operations",
    owner: "Maria Reyes",
    deadline: "2026-05-10",
    status: "Ongoing",
    riskLevel: "High",
    linkedGap: "Pipeline",
    module: "Workforce Hiring Plan",
    sourceType: "Manual",
    remarks:
      "Current sourced candidates are not enough to support approved hiring requirement.",
    requirement: 20,
    filled: 12,
    createdDate: "2026-05-03",
    completedDate: null,
  },
  {
    id: 2,
    actionId: "ACT-002",
    actionItem: "Schedule pending QA interviews within 48 hours.",
    roleAccount: "QA - SIBS Operations",
    roleTitle: "QA Specialist",
    account: "SIBS Operations",
    owner: "John Dela Cruz",
    deadline: "2026-05-08",
    status: "Planned",
    riskLevel: "High",
    linkedGap: "Interview",
    module: "Candidate Pipeline",
    sourceType: "Manual",
    remarks:
      "Interview delay is causing QA role to fall behind the workforce hiring plan.",
    requirement: 5,
    filled: 2,
    createdDate: "2026-05-04",
    completedDate: null,
  },
  {
    id: 3,
    actionId: "ACT-003",
    actionItem: "Review compensation range for System Developer applicants.",
    roleAccount: "System Developer - SIBS IT",
    roleTitle: "System Developer",
    account: "SIBS IT",
    owner: "Kim Domingo",
    deadline: "2026-05-09",
    status: "Ongoing",
    riskLevel: "Medium",
    linkedGap: "Offer",
    module: "Offers",
    sourceType: "Manual",
    remarks:
      "Offer declines are connected to compensation mismatch and competing offers.",
    requirement: 3,
    filled: 1,
    createdDate: "2026-05-02",
    completedDate: null,
  },
  {
    id: 4,
    actionId: "ACT-004",
    actionItem: "Finalize revised JD for RCM Analyst role.",
    roleAccount: "RCM Analyst - SIBS RCM",
    roleTitle: "RCM Analyst",
    account: "SIBS RCM",
    owner: "Paul Garcia",
    deadline: "2026-05-12",
    status: "Completed",
    riskLevel: "Low",
    linkedGap: "JD",
    module: "Job Description",
    sourceType: "Manual",
    remarks:
      "JD update completed and role is now aligned with sourcing requirements.",
    requirement: 5,
    filled: 3,
    createdDate: "2026-05-01",
    completedDate: "2026-05-06",
  },
  {
    id: 5,
    actionId: "ACT-005",
    actionItem:
      "Request approval confirmation for new HR Assistant headcount.",
    roleAccount: "HR Assistant - SIBS HR",
    roleTitle: "HR Assistant",
    account: "SIBS HR",
    owner: "Maria Reyes",
    deadline: "2026-05-11",
    status: "Planned",
    riskLevel: "Medium",
    linkedGap: "Approval",
    module: "Hiring Needs",
    sourceType: "Manual",
    remarks:
      "Hiring movement cannot proceed until approval status is finalized in the system.",
    requirement: 2,
    filled: 0,
    createdDate: "2026-05-05",
    completedDate: null,
  },
];
