export const fallbackWeeklyReports = [
  {
    id: 1,
    reportId: "WR-2026-W18",
    weekLabel: "Week 18, 2026",
    dateRange: "Apr 29 - May 5, 2026",
    status: "Generated",
    generatedDate: "2026-05-06",
    generatedBy: "System",
    totalOpenRoles: 5,
    totalRequirement: 35,
    totalFilled: 20,
    atRiskRoles: 2,
    delayedRoles: 2,
    dropOffs: 32,
    sourced: 181,
    screened: 103,
    interviewed: 49,
    offered: 21,
    accepted: 15,
    hired: 20,
    missingDataCount: 2,
    actionItemsCount: 5,
    publicApplicants: 0,
    talentPoolCount: 0,
    pendingHiringNeeds: 0,
    pendingOffers: 0,
    pendingOnboarding: 0,
    summary:
      "Hiring delivery is progressing but CSR, QA, and System Developer roles require immediate action due to risk and delay flags.",
    roles: [
      {
        role: "CSR",
        account: "SIBS Operations",
        requirement: 20,
        filled: 12,
        status: "At Risk",
        owner: "Maria Reyes",
      },
      {
        role: "QA Specialist",
        account: "SIBS Operations",
        requirement: 5,
        filled: 2,
        status: "Delayed",
        owner: "John Dela Cruz",
      },
      {
        role: "RCM Analyst",
        account: "SIBS RCM",
        requirement: 5,
        filled: 3,
        status: "On Track",
        owner: "Kim Domingo",
      },
    ],
    actionItems: [
      "Add 50 sourced candidates for CSR role before Friday.",
      "Schedule pending QA interviews within 48 hours.",
      "Review compensation range for System Developer applicants.",
    ],
    missingData: [
      "QA interview feedback is incomplete for 2 candidates.",
      "System Developer offer decline reason needs confirmation.",
    ],
  },
  {
    id: 2,
    reportId: "WR-2026-W17",
    weekLabel: "Week 17, 2026",
    dateRange: "Apr 22 - Apr 28, 2026",
    status: "Sent",
    generatedDate: "2026-04-29",
    generatedBy: "System",
    totalOpenRoles: 4,
    totalRequirement: 28,
    totalFilled: 16,
    atRiskRoles: 2,
    delayedRoles: 1,
    dropOffs: 26,
    sourced: 150,
    screened: 92,
    interviewed: 41,
    offered: 18,
    accepted: 12,
    hired: 16,
    missingDataCount: 1,
    actionItemsCount: 4,
    publicApplicants: 0,
    talentPoolCount: 0,
    pendingHiringNeeds: 0,
    pendingOffers: 0,
    pendingOnboarding: 0,
    summary:
      "Previous week showed stronger sourcing volume but interview conversion remained a concern.",
    roles: [
      {
        role: "CSR",
        account: "SIBS Operations",
        requirement: 18,
        filled: 10,
        status: "At Risk",
        owner: "Maria Reyes",
      },
      {
        role: "QA Specialist",
        account: "SIBS Operations",
        requirement: 5,
        filled: 1,
        status: "Delayed",
        owner: "John Dela Cruz",
      },
    ],
    actionItems: [
      "Increase sourcing for QA role.",
      "Review interview schedule delays.",
    ],
    missingData: ["One candidate drop-off reason was not categorized."],
  },
  {
    id: 3,
    reportId: "WR-2026-W16",
    weekLabel: "Week 16, 2026",
    dateRange: "Apr 15 - Apr 21, 2026",
    status: "Archived",
    generatedDate: "2026-04-22",
    generatedBy: "System",
    totalOpenRoles: 3,
    totalRequirement: 20,
    totalFilled: 14,
    atRiskRoles: 1,
    delayedRoles: 1,
    dropOffs: 18,
    sourced: 120,
    screened: 74,
    interviewed: 35,
    offered: 15,
    accepted: 10,
    hired: 14,
    missingDataCount: 0,
    actionItemsCount: 3,
    publicApplicants: 0,
    talentPoolCount: 0,
    pendingHiringNeeds: 0,
    pendingOffers: 0,
    pendingOnboarding: 0,
    summary:
      "Hiring progress was stable with fewer missing data issues compared to later weeks.",
    roles: [
      {
        role: "CSR",
        account: "SIBS Operations",
        requirement: 15,
        filled: 11,
        status: "On Track",
        owner: "Maria Reyes",
      },
    ],
    actionItems: ["Maintain CSR sourcing pipeline."],
    missingData: [],
  },
];
