import {
  Award,
  BadgeCheck,
  BookOpen,
  Briefcase,
  FileCheck2,
  FileText,
  GraduationCap,
  Heart,
  Lock,
  Phone,
  Sparkles,
  User,
} from "lucide-react";

export const PROFILE_TABS = [
  {
    key: "personal",
    label: "Personal Info",
    icon: User,
    children: [
      { key: "personal.basic", label: "Basic Info" },
      { key: "personal.contact", label: "Contact" },
      { key: "personal.address", label: "Address" },
      { key: "personal.ids", label: "Government IDs" },
    ],
  },
  {
    key: "family",
    label: "Family",
    icon: Heart,
    children: [
      { key: "family.spouse", label: "Spouse" },
      { key: "family.parents", label: "Parents" },
      { key: "family.children", label: "Children" },
      { key: "family.emergency", label: "Emergency Contact" },
    ],
  },
  { key: "education", label: "Education", icon: GraduationCap },
  { key: "eligibility", label: "Credentials", icon: Award },
  { key: "experience", label: "Experience", icon: Briefcase },
  { key: "training", label: "Trainings", icon: BookOpen },
  {
    key: "skills",
    label: "Skills / Awards",
    icon: Sparkles,
    children: [
      { key: "skills.skills", label: "Skills" },
      { key: "skills.recognitions", label: "Recognition" },
      { key: "skills.organizations", label: "Organizations" },
    ],
  },
  { key: "references", label: "References", icon: Phone },
  {
    key: "application",
    label: "Application & HR",
    icon: FileCheck2,
    children: [
      { key: "application.overview", label: "Overview" },
      { key: "application.pipeline", label: "Pipeline" },
      { key: "application.assessment", label: "Assessment" },
      { key: "application.history", label: "Status History" },
    ],
  },
  { key: "documents", label: "Documents", icon: FileText },
  { key: "notes", label: "Profile Notes", icon: Lock },
];

export const EDUCATION_LEVEL_OPTIONS = [
  "Elementary",
  "Secondary",
  "Senior High",
  "Vocational",
  "College Level",
  "College Graduate",
  "Graduate Studies",
];

export const PIPELINE_STAGES = [
  "Sourcing",
  "Initial Screening",
  "Evaluation",
  "Final Interview",
  "Onboarding",
  "Completed",
];

export const RECORD_SCHEMAS = {
  education: {
    title: "Education Chronological Records",
    subtitle: "Comprehensive academic qualifications and school history.",
    icon: GraduationCap,
    listKey: "education",
    addLabel: "Add Education Record",
    empty: "No education records found.",
    newRecord: {
      level: "College Graduate",
      school: "",
      degree: "",
      from: "",
      to: "",
      highestLevel: "",
      yearGraduated: "",
      honors: "",
    },
    fields: [
      ["level", "Level", "select", EDUCATION_LEVEL_OPTIONS],
      ["school", "Name of School"],
      ["degree", "Degree / Course"],
      ["from", "From"],
      ["to", "To"],
      ["highestLevel", "Highest Level / Units Earned"],
      ["yearGraduated", "Year Graduated"],
      ["honors", "Honors Received"],
    ],
  },
  eligibility: {
    title: "Eligibility Chronological Records",
    subtitle: "Professional licenses, examination ratings, and validity records.",
    icon: BadgeCheck,
    listKey: "eligibility",
    addLabel: "Add Eligibility Record",
    empty: "No eligibility or license records found.",
    newRecord: { title: "", rating: "", examDate: "", examPlace: "", licenseNumber: "", validityDate: "" },
    fields: [
      ["title", "Eligibility / License"],
      ["rating", "Rating"],
      ["examDate", "Date of Exam / Conferment", "date"],
      ["examPlace", "Place of Exam / Conferment"],
      ["licenseNumber", "License Number"],
      ["validityDate", "Validity Date", "date"],
    ],
  },
  experience: {
    title: "Experience Chronological Records",
    subtitle: "Previous corporate engagements, roles, compensation, and duties.",
    icon: Briefcase,
    listKey: "experience",
    addLabel: "Add Experience Record",
    empty: "No work experience records found.",
    newRecord: { from: "", to: "", position: "", company: "", salary: "", salaryGrade: "", appointmentStatus: "", governmentService: "No", duties: "" },
    fields: [
      ["from", "From", "month"],
      ["to", "To", "month"],
      ["position", "Position Title"],
      ["company", "Company / Office"],
      ["salary", "Monthly Salary"],
      ["salaryGrade", "Salary / Job Grade"],
      ["appointmentStatus", "Status of Appointment"],
      ["governmentService", "Government Service Y/N", "select", ["Yes", "No"]],
      ["duties", "Duties", "textarea"],
    ],
  },
  training: {
    title: "Training Chronological Records",
    subtitle: "Learning and development programs, hours, and sponsors.",
    icon: Award,
    listKey: "trainings",
    addLabel: "Add Training Record",
    empty: "No training records found.",
    newRecord: { title: "", from: "", to: "", hours: "", type: "", conductedBy: "" },
    fields: [
      ["title", "Training Title"],
      ["from", "From", "date"],
      ["to", "To", "date"],
      ["hours", "Number of Hours"],
      ["type", "Type of LD"],
      ["conductedBy", "Conducted / Sponsored By"],
    ],
  },
  references: {
    title: "References Chronological Records",
    subtitle: "Professional and character references for background verification.",
    icon: User,
    listKey: "references",
    addLabel: "Add Reference",
    empty: "No references found.",
    newRecord: { name: "", address: "", telephone: "" },
    fields: [
      ["name", "Name"],
      ["address", "Address"],
      ["telephone", "Telephone Number"],
    ],
  },
};
