import React, { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { approveRevisedOffer, getRevisedOfferApproval, rejectRevisedOffer } from "../../../lib/axios/candidateOfferRevisions";

const peso = (value) => `₱${Number(value || 0).toLocaleString("en-PH", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

export default function RevisedOfferApprovalPage() {
  const { token } = useParams();
  const [data,setData]=useState(null); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState("");
  useEffect(()=>{ getRevisedOfferApproval(token).then((r)=>setData(r.approval)).catch((e)=>setError(e?.response?.data?.message||e.message)).finally(()=>setLoading(false)); },[token]);
  async function approve(){ setBusy(true); setError(""); try{const r=await approveRevisedOffer(token);setMessage(r.message);}catch(e){setError(e?.response?.data?.message||e.message);}finally{setBusy(false);} }
  async function reject(){ const reason=window.prompt("Enter the rejection reason:"); if(!reason)return; setBusy(true); try{const r=await rejectRevisedOffer(token,reason);setMessage(r.message);}catch(e){setError(e?.response?.data?.message||e.message);}finally{setBusy(false);} }
  if(loading)return <main className="grid min-h-screen place-items-center bg-slate-50 text-sm font-bold text-sibs-navy font-jakarta">Loading revised offer...</main>;
  if(error&&!data)return <main className="grid min-h-screen place-items-center bg-slate-50 p-6 font-jakarta"><div className="max-w-md rounded-[14px] border border-sibs-border bg-white p-6 text-center shadow"><h1 className="font-extrabold text-red-700">Unable to Open Approval</h1><p className="mt-2 text-sm text-sibs-muted">{error}</p></div></main>;
  const c=data.currentOffer||{}, r=data.revisedOffer||{};
  return <main className="min-h-screen bg-slate-50 p-6 font-jakarta"><section className="mx-auto max-w-3xl overflow-hidden rounded-[14px] border border-sibs-border bg-white shadow-xl"><header className="bg-sibs-navy p-6 text-white"><p className="text-xs font-extrabold uppercase tracking-widest">SiBS HRIS Approval</p><h1 className="mt-2 text-2xl font-extrabold">Revised Offer Review</h1><p className="mt-1 text-sm text-blue-100">{data.candidate?.name}</p></header><div className="space-y-5 p-6"><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-[10px] bg-slate-50 p-4"><h2 className="text-xs font-extrabold uppercase text-sibs-muted">Current Compensation</h2><p className="mt-3 text-sm font-bold">Basic Daily Rate: {peso(c.basicDailyRate)}</p><p className="mt-2 text-sm font-bold">Daily De Minimis: {peso(c.dailyDeMinimis)}</p></div><div className="rounded-[10px] bg-blue-50 p-4"><h2 className="text-xs font-extrabold uppercase text-blue-700">Proposed Compensation</h2><p className="mt-3 text-sm font-bold">Basic Daily Rate: {peso(r.basicDailyRate)}</p><p className="mt-2 text-sm font-bold">Daily De Minimis: {peso(r.dailyDeMinimis)}</p></div></div>{r.remarks&&<div className="rounded-[10px] border border-sibs-border p-4"><p className="text-xs font-extrabold uppercase text-sibs-muted">Recruiter remarks</p><p className="mt-2 text-sm font-semibold">{r.remarks}</p></div>}{message&&<p className="rounded-[10px] bg-emerald-50 p-4 text-sm font-bold text-emerald-700">{message}</p>}{error&&<p className="rounded-[10px] bg-red-50 p-4 text-sm font-bold text-red-700">{error}</p>}<div className="flex justify-end gap-3"><button disabled={busy||message} onClick={reject} className="h-11 rounded-[10px] border border-red-200 px-5 text-sm font-extrabold text-red-700 transition hover:bg-red-50">Reject</button><button disabled={busy||message} onClick={approve} className="h-11 rounded-[10px] bg-sibs-navy px-5 text-sm font-extrabold text-white transition hover:bg-sibs-navy-light">{busy?"Processing...":"Approve Revised Offer"}</button></div></div></section></main>;
}
