/**
 * Static / sample offer records for purely frontend demonstration in SiBS HRIS.
 * Provides realistic end-to-end recruitment offer lifecycle data across various
 * accounts, roles, compensation rates, negotiation versions, and approval states.
 */

export const sampleOfferCandidates = [
  {
    id: "offer-static-101",
    dbId: "offer-static-101",
    pipelineDbId: "offer-static-101",
    candidatePipelineId: "offer-static-101",
    candidateApplicationId: "APP-2026-101",
    candidateId: "CAN-2026-101",
    candidateName: "Maria Santos",
    candidateEmail: "maria.santos@email.com",
    contactNumber: "+63 917 123 4567",
    currentStage: "Offered",
    currentPipelineStage: "Offered",
    stage: "Offered",
    pipelineStage: "Offered",
    roleTitle: "Customer Service Representative",
    currentAppliedRole: "Customer Service Representative",
    openPosition: "Customer Service Representative",
    account: "Connect",
    currentAppliedAccount: "Connect",
    roleAccount: "Customer Service Representative / Connect",
    hiringRequirementId: "REQ-2026-001",
    basicPay: "680.00",
    deminimisDailyRate: "120.00",
    startDate: "2026-09-01",
    remarks: "Passed all evaluation stages with exceptional communication skills.",
    offerDetails: {
      offerId: "OFF-2026-101",
      roleTitle: "Customer Service Representative",
      account: "Connect",
      hiringRequirementId: "REQ-2026-001",
      basicPay: "680.00",
      deminimisDailyRate: "120.00",
      startDate: "2026-09-01",
      remarks: "Prepared offer for standard CSR package.",
    },
    offerApprovals: {
      "RAUL NADELA": {
        status: "Pending",
        remarks: "Pending executive review",
      },
    },
    approvals: {
      "RAUL NADELA": {
        status: "Pending",
        remarks: "Pending executive review",
      },
    },
    offerApprovalStatus: "For Review",
    approvalStatus: "For Review",
    status: "For Review",
    offerDecision: "Pending",
    candidateResponse: "Pending",
    offerResponseStatus: "Pending",
    offerEmailSent: false,
    offerEmailSentAt: "",
    owner: "Raul Nadela",
    assessmentScore: 88,
    assessmentMaxScore: 100,
    assessmentResult: "Passed",
    jobEvaluationScore: 86,
    jobEvaluationMaxScore: 100,
    jobEvaluationRank: "1",
    finalInterviewScore: 92,
    finalInterviewMaxScore: 100,
    finalInterviewResult: "Passed",
    finalInterviewPassingScore: 80,
    offerHistory: [
      {
        id: "v1-101",
        versionNumber: 1,
        roleTitle: "Customer Service Representative",
        account: "Connect",
        basicDailyRate: 680,
        dailyDeMinimis: 120,
        totalDailyRate: 800,
        candidateMessage: "",
        internalRemarks: "Initial offer prepared for standard entry-level CSR.",
        approvalStatus: "For Review",
        candidateResponse: "Pending",
        submittedBy: "Raul Nadela",
        submittedAt: "2026-08-24T08:30:00.000Z",
        offerEmailSent: false,
        pdfAvailable: true,
      },
    ],
  },
  {
    id: "offer-static-102",
    dbId: "offer-static-102",
    pipelineDbId: "offer-static-102",
    candidatePipelineId: "offer-static-102",
    candidateApplicationId: "APP-2026-102",
    candidateId: "CAN-2026-102",
    candidateName: "John Christian Reyes",
    candidateEmail: "jc.reyes@email.com",
    contactNumber: "+63 918 234 5678",
    currentStage: "Offered",
    currentPipelineStage: "Offered",
    stage: "Offered",
    pipelineStage: "Offered",
    roleTitle: "Technical Support Specialist",
    currentAppliedRole: "Technical Support Specialist",
    openPosition: "Technical Support Specialist",
    account: "Collect IV",
    currentAppliedAccount: "Collect IV",
    roleAccount: "Technical Support Specialist / Collect IV",
    hiringRequirementId: "REQ-2026-002",
    basicPay: "750.00",
    deminimisDailyRate: "150.00",
    startDate: "2026-09-08",
    remarks: "Approved by TA Head. Ready to dispatch employment contract.",
    offerDetails: {
      offerId: "OFF-2026-102",
      roleTitle: "Technical Support Specialist",
      account: "Collect IV",
      hiringRequirementId: "REQ-2026-002",
      basicPay: "750.00",
      deminimisDailyRate: "150.00",
      startDate: "2026-09-08",
    },
    offerApprovals: {
      "RAUL NADELA": {
        status: "Approved",
        approvedBy: "Raul Nadela",
        approvedAt: "2026-08-25T10:15:00.000Z",
        remarks: "Approved package for Tier 2 technical profile.",
      },
    },
    approvals: {
      "RAUL NADELA": {
        status: "Approved",
        approvedBy: "Raul Nadela",
        approvedAt: "2026-08-25T10:15:00.000Z",
        remarks: "Approved package for Tier 2 technical profile.",
      },
    },
    offerApprovalStatus: "Approved",
    approvalStatus: "Approved",
    status: "Approved",
    offerDecision: "Pending",
    candidateResponse: "Pending",
    offerResponseStatus: "Pending",
    offerEmailSent: false,
    offerEmailSentAt: "",
    owner: "Haasanor",
    assessmentScore: 94,
    assessmentMaxScore: 100,
    assessmentResult: "Passed",
    jobEvaluationScore: 91,
    jobEvaluationMaxScore: 100,
    jobEvaluationRank: "1",
    finalInterviewScore: 95,
    finalInterviewMaxScore: 100,
    finalInterviewResult: "Passed",
    finalInterviewPassingScore: 80,
    offerHistory: [
      {
        id: "v1-102",
        versionNumber: 1,
        roleTitle: "Technical Support Specialist",
        account: "Collect IV",
        basicDailyRate: 750,
        dailyDeMinimis: 150,
        totalDailyRate: 900,
        candidateMessage: "",
        internalRemarks: "Standard compensation package for technical support tier.",
        approvalStatus: "Approved",
        approvedBy: "Raul Nadela",
        approvedAt: "2026-08-25T10:15:00.000Z",
        approvalRemarks: "Approved package for Tier 2 technical profile.",
        candidateResponse: "Pending",
        submittedBy: "Haasanor",
        submittedAt: "2026-08-24T14:00:00.000Z",
        offerEmailSent: false,
        pdfAvailable: true,
      },
    ],
  },
  {
    id: "offer-static-103",
    dbId: "offer-static-103",
    pipelineDbId: "offer-static-103",
    candidatePipelineId: "offer-static-103",
    candidateApplicationId: "APP-2026-103",
    candidateId: "CAN-2026-103",
    candidateName: "Angela Mae Del Rosario",
    candidateEmail: "angela.delrosario@email.com",
    contactNumber: "+63 920 345 6789",
    currentStage: "Offered",
    currentPipelineStage: "Offered",
    stage: "Offered",
    pipelineStage: "Offered",
    roleTitle: "Healthcare Account Associate",
    currentAppliedRole: "Healthcare Account Associate",
    openPosition: "Healthcare Account Associate",
    account: "DentistRX",
    currentAppliedAccount: "DentistRX",
    roleAccount: "Healthcare Account Associate / DentistRX",
    hiringRequirementId: "REQ-2026-003",
    basicPay: "800.00",
    deminimisDailyRate: "150.00",
    startDate: "2026-09-01",
    remarks: "Employment contract sent via email. Awaiting candidate signature.",
    offerDetails: {
      offerId: "OFF-2026-103",
      roleTitle: "Healthcare Account Associate",
      account: "DentistRX",
      hiringRequirementId: "REQ-2026-003",
      basicPay: "800.00",
      deminimisDailyRate: "150.00",
      startDate: "2026-09-01",
    },
    offerApprovals: {
      "RAUL NADELA": {
        status: "Approved",
        approvedBy: "Raul Nadela",
        approvedAt: "2026-08-23T11:00:00.000Z",
        remarks: "Approved for healthcare premium account.",
      },
    },
    approvals: {
      "RAUL NADELA": {
        status: "Approved",
        approvedBy: "Raul Nadela",
        approvedAt: "2026-08-23T11:00:00.000Z",
        remarks: "Approved for healthcare premium account.",
      },
    },
    offerApprovalStatus: "Approved",
    approvalStatus: "Approved",
    status: "Contract Sent",
    offerDecision: "Pending",
    candidateResponse: "Pending",
    offerResponseStatus: "Pending",
    offerEmailSent: true,
    offerEmailSentAt: "2026-08-23T14:30:00.000Z",
    owner: "Raul Nadela",
    assessmentScore: 90,
    assessmentMaxScore: 100,
    assessmentResult: "Passed",
    jobEvaluationScore: 88,
    jobEvaluationMaxScore: 100,
    jobEvaluationRank: "2",
    finalInterviewScore: 91,
    finalInterviewMaxScore: 100,
    finalInterviewResult: "Passed",
    finalInterviewPassingScore: 80,
    offerHistory: [
      {
        id: "v1-103",
        versionNumber: 1,
        roleTitle: "Healthcare Account Associate",
        account: "DentistRX",
        basicDailyRate: 800,
        dailyDeMinimis: 150,
        totalDailyRate: 950,
        candidateMessage: "",
        internalRemarks: "Offer approved and contract officially dispatched.",
        approvalStatus: "Approved",
        approvedBy: "Raul Nadela",
        approvedAt: "2026-08-23T11:00:00.000Z",
        approvalRemarks: "Approved for healthcare premium account.",
        candidateResponse: "Pending",
        submittedBy: "Raul Nadela",
        submittedAt: "2026-08-23T09:00:00.000Z",
        offerEmailSent: true,
        offerSentAt: "2026-08-23T14:30:00.000Z",
        pdfAvailable: true,
      },
    ],
  },
  {
    id: "offer-static-104",
    dbId: "offer-static-104",
    pipelineDbId: "offer-static-104",
    candidatePipelineId: "offer-static-104",
    candidateApplicationId: "APP-2026-104",
    candidateId: "CAN-2026-104",
    candidateName: "Mark Kevin Bautista",
    candidateEmail: "mark.bautista@email.com",
    contactNumber: "+63 921 456 7890",
    currentStage: "Offered",
    currentPipelineStage: "Offered",
    stage: "Offered",
    pipelineStage: "Offered",
    roleTitle: "Financial Account Associate",
    currentAppliedRole: "Financial Account Associate",
    openPosition: "Financial Account Associate",
    account: "Cash",
    currentAppliedAccount: "Cash",
    roleAccount: "Financial Account Associate / Cash",
    hiringRequirementId: "REQ-2026-004",
    basicPay: "850.00",
    deminimisDailyRate: "150.00",
    startDate: "2026-09-15",
    remarks: "Candidate requested revision on Daily De Minimis due to travel distance.",
    offerDetails: {
      offerId: "OFF-2026-104",
      roleTitle: "Financial Account Associate",
      account: "Cash",
      hiringRequirementId: "REQ-2026-004",
      basicPay: "850.00",
      deminimisDailyRate: "150.00",
      startDate: "2026-09-15",
    },
    offerApprovals: {
      "RAUL NADELA": {
        status: "Pending",
        remarks: "Reviewing counter-offer",
      },
    },
    approvals: {
      "RAUL NADELA": {
        status: "Pending",
        remarks: "Reviewing counter-offer",
      },
    },
    offerApprovalStatus: "For Review",
    approvalStatus: "For Review",
    status: "Negotiation",
    offerDecision: "Negotiation Requested",
    candidateResponse: "Negotiation Requested",
    offerResponseStatus: "Negotiation Requested",
    offerNegotiationMessage: "Candidate requested an adjustment on daily de minimis due to transportation costs from Tagum.",
    offerEmailSent: true,
    offerEmailSentAt: "2026-08-22T16:00:00.000Z",
    owner: "Haasanor",
    assessmentScore: 85,
    assessmentMaxScore: 100,
    assessmentResult: "Passed",
    jobEvaluationScore: 82,
    jobEvaluationMaxScore: 100,
    jobEvaluationRank: "3",
    finalInterviewScore: 88,
    finalInterviewMaxScore: 100,
    finalInterviewResult: "Passed",
    finalInterviewPassingScore: 80,
    offerHistory: [
      {
        id: "v2-104",
        versionNumber: 2,
        parentVersionNumber: 1,
        previousBasicDailyRate: 800,
        previousDailyDeMinimis: 100,
        roleTitle: "Financial Account Associate",
        account: "Cash",
        basicDailyRate: 850,
        dailyDeMinimis: 150,
        totalDailyRate: 1000,
        candidateMessage: "Candidate requested an adjustment on daily de minimis due to transportation costs from Tagum.",
        internalRemarks: "Adjusted compensation upward by PHP 100 daily rate to accommodate travel distance.",
        approvalStatus: "For Review",
        candidateResponse: "Pending",
        submittedBy: "Haasanor",
        submittedAt: "2026-08-25T11:20:00.000Z",
        offerEmailSent: false,
        pdfAvailable: true,
      },
      {
        id: "v1-104",
        versionNumber: 1,
        roleTitle: "Financial Account Associate",
        account: "Cash",
        basicDailyRate: 800,
        dailyDeMinimis: 100,
        totalDailyRate: 900,
        candidateMessage: "Can we adjust the daily allowance for transportation?",
        internalRemarks: "Initial offer dispatched.",
        approvalStatus: "Approved",
        approvedBy: "Raul Nadela",
        approvedAt: "2026-08-22T15:00:00.000Z",
        candidateResponse: "Negotiation Requested",
        submittedBy: "Haasanor",
        submittedAt: "2026-08-22T10:00:00.000Z",
        offerEmailSent: true,
        offerSentAt: "2026-08-22T16:00:00.000Z",
        pdfAvailable: true,
      },
    ],
  },
  {
    id: "offer-static-105",
    dbId: "offer-static-105",
    pipelineDbId: "offer-static-105",
    candidatePipelineId: "offer-static-105",
    candidateApplicationId: "APP-2026-105",
    candidateId: "CAN-2026-105",
    candidateName: "Patricia Nicole Lim",
    candidateEmail: "patricia.lim@email.com",
    contactNumber: "+63 922 567 8901",
    currentStage: "Offered",
    currentPipelineStage: "Offered",
    stage: "Offered",
    pipelineStage: "Offered",
    roleTitle: "Customer Experience Representative",
    currentAppliedRole: "Customer Experience Representative",
    openPosition: "Customer Experience Representative",
    account: "US Visa",
    currentAppliedAccount: "US Visa",
    roleAccount: "Customer Experience Representative / US Visa",
    hiringRequirementId: "REQ-2026-005",
    basicPay: "720.00",
    deminimisDailyRate: "130.00",
    startDate: "2026-09-01",
    remarks: "Compensation request exceeded approved client budget band.",
    offerDetails: {
      offerId: "OFF-2026-105",
      roleTitle: "Customer Experience Representative",
      account: "US Visa",
      hiringRequirementId: "REQ-2026-005",
      basicPay: "720.00",
      deminimisDailyRate: "130.00",
      startDate: "2026-09-01",
    },
    offerApprovals: {
      "RAUL NADELA": {
        status: "Rejected",
        rejectedBy: "Raul Nadela",
        rejectedAt: "2026-08-24T16:00:00.000Z",
        remarks: "Proposed rate is above max budget cap for this batch.",
      },
    },
    approvals: {
      "RAUL NADELA": {
        status: "Rejected",
        rejectedBy: "Raul Nadela",
        rejectedAt: "2026-08-24T16:00:00.000Z",
        remarks: "Proposed rate is above max budget cap for this batch.",
      },
    },
    offerApprovalStatus: "Rejected",
    approvalStatus: "Rejected",
    status: "Rejected",
    offerDecision: "Rejected",
    candidateResponse: "Pending",
    offerResponseStatus: "Pending",
    offerEmailSent: false,
    owner: "Raul Nadela",
    assessmentScore: 78,
    assessmentMaxScore: 100,
    assessmentResult: "Passed",
    jobEvaluationScore: 75,
    jobEvaluationMaxScore: 100,
    jobEvaluationRank: "4",
    finalInterviewScore: 82,
    finalInterviewMaxScore: 100,
    finalInterviewResult: "Passed",
    finalInterviewPassingScore: 80,
    offerHistory: [
      {
        id: "v1-105",
        versionNumber: 1,
        roleTitle: "Customer Experience Representative",
        account: "US Visa",
        basicDailyRate: 720,
        dailyDeMinimis: 130,
        totalDailyRate: 850,
        candidateMessage: "",
        internalRemarks: "Proposed rate exceeded budget tier.",
        approvalStatus: "Rejected",
        rejectedBy: "Raul Nadela",
        rejectedAt: "2026-08-24T16:00:00.000Z",
        approvalRemarks: "Proposed rate is above max budget cap for this batch.",
        candidateResponse: "Pending",
        submittedBy: "Raul Nadela",
        submittedAt: "2026-08-24T11:00:00.000Z",
        offerEmailSent: false,
        pdfAvailable: true,
      },
    ],
  },
  {
    id: "offer-static-106",
    dbId: "offer-static-106",
    pipelineDbId: "offer-static-106",
    candidatePipelineId: "offer-static-106",
    candidateApplicationId: "APP-2026-106",
    candidateId: "CAN-2026-106",
    candidateName: "Dexter James Alcantara",
    candidateEmail: "dexter.alcantara@email.com",
    contactNumber: "+63 923 678 9012",
    currentStage: "Offered",
    currentPipelineStage: "Offered",
    stage: "Offered",
    pipelineStage: "Offered",
    roleTitle: "Lead Generation Specialist",
    currentAppliedRole: "Lead Generation Specialist",
    openPosition: "Lead Generation Specialist",
    account: "Channel Assist",
    currentAppliedAccount: "Channel Assist",
    roleAccount: "Lead Generation Specialist / Channel Assist",
    hiringRequirementId: "REQ-2026-006",
    basicPay: "700.00",
    deminimisDailyRate: "120.00",
    startDate: "2026-09-01",
    remarks: "Candidate declined offer due to competing opportunity with dayshift hours.",
    offerDetails: {
      offerId: "OFF-2026-106",
      roleTitle: "Lead Generation Specialist",
      account: "Channel Assist",
      hiringRequirementId: "REQ-2026-006",
      basicPay: "700.00",
      deminimisDailyRate: "120.00",
      startDate: "2026-09-01",
    },
    offerApprovals: {
      "RAUL NADELA": {
        status: "Approved",
        approvedBy: "Raul Nadela",
        approvedAt: "2026-08-21T09:30:00.000Z",
      },
    },
    approvals: {
      "RAUL NADELA": {
        status: "Approved",
        approvedBy: "Raul Nadela",
        approvedAt: "2026-08-21T09:30:00.000Z",
      },
    },
    offerApprovalStatus: "Approved",
    approvalStatus: "Approved",
    status: "Declined",
    offerDecision: "Declined",
    candidateResponse: "Declined",
    offerResponseStatus: "Declined",
    declineCategory: "Accepted Other Offer",
    declineReason: "Candidate accepted another competing offer with immediate day shift schedule.",
    candidateFeedback: "The recruitment team was very communicative and professional throughout.",
    experienceRating: 5,
    feedbackTag: "Offer Declined - Schedule Preference",
    offerEmailSent: true,
    offerEmailSentAt: "2026-08-21T11:00:00.000Z",
    owner: "Haasanor",
    assessmentScore: 89,
    assessmentMaxScore: 100,
    assessmentResult: "Passed",
    jobEvaluationScore: 84,
    jobEvaluationMaxScore: 100,
    jobEvaluationRank: "2",
    finalInterviewScore: 89,
    finalInterviewMaxScore: 100,
    finalInterviewResult: "Passed",
    finalInterviewPassingScore: 80,
    offerHistory: [
      {
        id: "v1-106",
        versionNumber: 1,
        roleTitle: "Lead Generation Specialist",
        account: "Channel Assist",
        basicDailyRate: 700,
        dailyDeMinimis: 120,
        totalDailyRate: 820,
        candidateMessage: "Thank you for the offer, but I have decided to accept an offer with day shift hours.",
        internalRemarks: "Candidate declined offer following formal contract release.",
        approvalStatus: "Approved",
        approvedBy: "Raul Nadela",
        approvedAt: "2026-08-21T09:30:00.000Z",
        candidateResponse: "Declined",
        submittedBy: "Haasanor",
        submittedAt: "2026-08-21T08:30:00.000Z",
        offerEmailSent: true,
        offerSentAt: "2026-08-21T11:00:00.000Z",
        pdfAvailable: true,
      },
    ],
  },
];
