import React from "react";
import { AlertTriangle, CheckSquare, Eye } from "lucide-react";
import { DataCard } from "@/components/ui";

function getReportStatusClass(status) {
  if (status === "Generated") return "border-amber-200 bg-amber-50 text-amber-700";
  if (status === "Sent") return "border-emerald-200 bg-emerald-50 text-emerald-700";
  if (status === "Archived") return "border-slate-200 bg-slate-100 text-slate-600";
  return "border-slate-200 bg-slate-50 text-slate-600";
}

function toNumber(value) {
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : 0;
}

export default function WeeklyReportMobileCard({
  report,
  onView,
  delay = 0,
  index = 0,
}) {
  const requirement = toNumber(report?.totalRequirement);
  const filled = toNumber(report?.totalFilled);
  const fulfillment = requirement > 0 ? Math.round((filled / requirement) * 100) : 0;
  const actionCount = toNumber(report?.actionItemsCount);
  const missingCount = toNumber(report?.missingDataCount);

  return (
    <DataCard
      index={index}
      style={delay ? { animationDelay: `${delay}ms`, animationFillMode: "both" } : undefined}
      onClick={onView}
    >
      <DataCard.Header
        kicker={report.reportId}
        title={report.weekLabel}
        subtitle={report.dateRange}
        badge={
          <span
            className={`shrink-0 rounded-full border px-2.5 py-0.5 text-[9px] font-extrabold uppercase ${getReportStatusClass(
              report.status
            )}`}
          >
            {report.status}
          </span>
        }
      />

      <DataCard.ContextRow>
        <div className="flex items-center justify-between text-[11px] font-semibold text-[#667085]">
          <span>Generated by {report.generatedBy || "System"}</span>
          <span className="font-mono text-[10px] text-[#98A2B3]">{report.reportId}</span>
        </div>
      </DataCard.ContextRow>

      <div className="mt-2.5 rounded-xl border border-[#E6ECF2] bg-[#F8FAFC] p-3">
        <div className="flex items-center justify-between gap-3">
          <div>
            <p className="text-[9px] font-extrabold uppercase text-[#98A2B3]">
              Requirement vs. Filled
            </p>
            <p className="mt-1 text-sm font-extrabold text-[#042C51]">
              <span className="text-emerald-700">{filled}</span> / {requirement}
            </p>
          </div>
          <span className="rounded-md bg-white px-2 py-1 text-[10px] font-extrabold text-[#FF5C28] shadow-xs">
            {fulfillment}%
          </span>
        </div>
        <div className="mt-2 h-1.5 overflow-hidden rounded-full bg-[#E6ECF2]">
          <div
            className="h-full rounded-full bg-[#FF5C28]"
            style={{ width: `${Math.max(0, Math.min(100, fulfillment))}%` }}
          />
        </div>
      </div>

      <div className="mt-3 flex flex-wrap gap-1.5">
        <span className="inline-flex items-center gap-1 rounded-md border border-orange-200 bg-orange-50 px-2 py-1 text-[9px] font-extrabold text-orange-700">
          <CheckSquare size={11} className="text-[#FF5C28]" />
          {actionCount} Tasks
        </span>
        {missingCount > 0 && (
          <span className="inline-flex items-center gap-1 rounded-md border border-red-200 bg-red-50 px-2 py-1 text-[9px] font-extrabold text-red-700">
            <AlertTriangle size={11} />
            {missingCount} Alerts
          </span>
        )}
      </div>

      <DataCard.Footer
        meta={
          <span className="text-[10px] font-bold text-[#667085]">
            Fulfillment Rate: {fulfillment}%
          </span>
        }
        actionText="View Details"
      />
    </DataCard>
  );
}

