import { AlertTriangle, CheckSquare, Eye } from "lucide-react";


function getReportStatusClass(status) {
  if (status === "Generated") return "border-amber-200 bg-amber-50 text-amber-700";
  if (status === "Sent") return "border-emerald-200 bg-emerald-50 text-emerald-700";
  if (status === "Archived") return "border-slate-200 bg-slate-100 text-slate-600";
  return "border-slate-200 bg-slate-50 text-slate-600";
}

function toNumber(value) {
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : 0;
}

export default function WeeklyReportMobileCard({ report, onView, delay = 0 }) {
  const requirement = toNumber(report.totalRequirement);
  const filled = toNumber(report.totalFilled);
  const fulfillment = requirement > 0 ? Math.round((filled / requirement) * 100) : 0;

  return (
    <button
      type="button"
      onClick={onView}
      className="sibs-page-card-in w-full rounded-2xl border border-[#E6ECF2] bg-white p-4 text-left shadow-sm transition-all duration-200 hover:-translate-y-0.5 hover:border-[#FF5C28]/30 hover:bg-[#FFFDFC] hover:shadow-md active:scale-[0.98]"
      style={{ animationDelay: `${delay}ms`, animationFillMode: "both" }}
    >
      <div className="flex items-start justify-between gap-3">
        <div className="min-w-0">
          <p className="font-mono text-[10px] font-extrabold text-[#667085]">{report.reportId}</p>
          <h3 className="mt-1 text-sm font-extrabold text-sibs-primary-1">{report.weekLabel}</h3>
          <p className="mt-1 text-xs font-semibold text-[#667085]">{report.dateRange}</p>
          <p className="mt-1 truncate text-[10px] font-semibold text-[#98A2B3]">
            Generated by {report.generatedBy || "System"}
          </p>
        </div>

        <span className={`shrink-0 rounded-full border px-2.5 py-1 text-[9px] font-extrabold uppercase ${getReportStatusClass(report.status)}`}>
          {report.status}
        </span>
      </div>

      <div className="mt-4 rounded-xl border border-[#E6ECF2] bg-[#F8FAFC] p-3">
        <div className="flex items-center justify-between gap-3">
          <div>
            <p className="text-[9px] font-extrabold uppercase text-[#98A2B3]">Requirement vs. Filled</p>
            <p className="mt-1 text-sm font-extrabold text-sibs-primary-1">
              <span className="text-emerald-700">{filled}</span> / {requirement}
            </p>
          </div>
          <span className="rounded-md bg-white px-2 py-1 text-[10px] font-extrabold text-[#FF5C28] shadow-sm">
            {fulfillment}%
          </span>
        </div>
        <div className="mt-2 h-1.5 overflow-hidden rounded-full bg-[#E6ECF2]">
          <div className="h-full rounded-full bg-[#FF5C28]" style={{ width: `${Math.max(0, Math.min(100, fulfillment))}%` }} />
        </div>
      </div>

      <div className="mt-3 flex flex-wrap gap-1.5">
        <span className="inline-flex items-center gap-1 rounded-md border border-orange-200 bg-orange-50 px-2 py-1 text-[9px] font-extrabold text-orange-700">
          <CheckSquare size={11} className="text-[#FF5C28]" />
          {toNumber(report.actionItemsCount)} Tasks
        </span>
        {toNumber(report.missingDataCount) > 0 ? (
          <span className="inline-flex items-center gap-1 rounded-md border border-red-200 bg-red-50 px-2 py-1 text-[9px] font-extrabold text-red-700">
            <AlertTriangle size={11} />
            {toNumber(report.missingDataCount)} Alerts
          </span>
        ) : null}
      </div>

      <div className="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-xl border border-blue-200 bg-[#E9F0FC] px-3 py-2 text-[10px] font-extrabold text-sibs-primary-1">
        <Eye size={14} className="text-[#FF5C28]" />
        View Details
      </div>
    </button>
  );
}
