import { CalendarDays, Eye } from "lucide-react";
import {
  formatDate,
  getStatusClass,
} from "../../../lib/utils/weeklyReports/weeklyReportsHelpers.js";
import WeeklyReportMobileCard from "./WeeklyReportMobileCard.jsx";

export default function WeeklyReportsTable({ reports, onView }) {
  return (
    <>
      <div className="space-y-3 lg:hidden">
        {reports.length > 0 ? (
          reports.map((report, index) => (
            <WeeklyReportMobileCard
              key={report.reportId}
              report={report}
              onView={() => onView(report)}
              delay={index * 60}
            />
          ))
        ) : (
          <div className="rounded-xl border border-[#E6ECF2] bg-white px-5 py-10 text-center text-sm font-bold text-gray-500">
            No weekly reports found.
          </div>
        )}
      </div>

      <div className="hidden lg:block">
        <div className="overflow-x-auto p-0">
          <table className="w-full min-w-[1180px] border-separate border-spacing-0 overflow-hidden rounded-2xl border border-[#D9E2EC] text-left">
            <thead>
              <tr className="bg-[#F5F7FA] text-xs font-bold uppercase tracking-wide text-[#174A7C]">
                <th className="px-5 py-4 first:rounded-tl-2xl">Report ID</th>
                <th className="px-5 py-4">Week</th>
                <th className="px-5 py-4">Date Range</th>
                <th className="px-5 py-4">Generated Date</th>
                <th className="px-5 py-4 text-center">Req.</th>
                <th className="px-5 py-4 text-center">Filled</th>
                <th className="px-5 py-4 text-center">At Risk</th>
                <th className="px-5 py-4 text-center">Delayed</th>
                <th className="px-5 py-4">Status</th>
                <th className="px-5 py-4 text-right last:rounded-tr-2xl">
                  Action
                </th>
              </tr>
            </thead>

            <tbody>
              {reports.length > 0 ? (
                reports.map((report) => (
                  <tr
                    key={report.reportId}
                    className="transition-all duration-200 hover:bg-[#FAFBFC]"
                  >
                    <td className="border-b border-[#E6ECF2] px-5 py-5 text-sm font-bold text-sibs-primary-1">
                      {report.reportId}
                    </td>

                    <td className="border-b border-[#E6ECF2] px-5 py-5">
                      <p className="text-sm font-bold text-[#101828]">
                        {report.weekLabel}
                      </p>

                      <p className="mt-1 text-xs font-semibold text-sibs-tertiary-5">
                        Generated by {report.generatedBy}
                      </p>
                    </td>

                    <td className="border-b border-[#E6ECF2] px-5 py-5 text-sm font-semibold text-[#344054]">
                      {report.dateRange}
                    </td>

                    <td className="border-b border-[#E6ECF2] px-5 py-5 text-sm font-semibold text-[#344054]">
                      <div className="flex items-center gap-2">
                        <CalendarDays size={15} className="text-gray-400" />
                        {formatDate(report.generatedDate)}
                      </div>
                    </td>

                    <td className="border-b border-[#E6ECF2] px-5 py-5 text-center text-sm font-bold text-[#344054]">
                      {report.totalRequirement}
                    </td>

                    <td className="border-b border-[#E6ECF2] px-5 py-5 text-center text-sm font-bold text-emerald-600">
                      {report.totalFilled}
                    </td>

                    <td className="border-b border-[#E6ECF2] px-5 py-5 text-center text-sm font-bold text-amber-600">
                      {report.atRiskRoles}
                    </td>

                    <td className="border-b border-[#E6ECF2] px-5 py-5 text-center text-sm font-bold text-red-600">
                      {report.delayedRoles}
                    </td>

                    <td className="border-b border-[#E6ECF2] px-5 py-5">
                      <span
                        className={`inline-flex rounded-full border px-3 py-1 text-xs font-bold ${getStatusClass(
                          report.status,
                        )}`}
                      >
                        {report.status}
                      </span>
                    </td>

                    <td className="border-b border-[#E6ECF2] px-5 py-5 text-right">
                      <button
                        type="button"
                        onClick={() => onView(report)}
                        className="inline-flex h-9 items-center justify-center gap-2 rounded-xl border border-[#D6DEE8] bg-white px-4 text-xs font-bold text-sibs-primary-1 transition-all duration-200 hover:-translate-y-0.5 hover:bg-[#F8FAFC] hover:shadow-sm active:scale-[0.98]"
                      >
                        <Eye size={15} />
                        Preview
                      </button>
                    </td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td
                    colSpan={10}
                    className="px-5 py-12 text-center text-sm font-bold text-gray-500"
                  >
                    No weekly reports found.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </>
  );
}
