export const EMAIL_LOGS = [
  {
    id: "EML-2026-0914-001",
    recipient: "Roman Cabanes Lausa",
    email: "cristersinanit1@gmail.com",
    role: "Candidate",
    site: "Tagum City Campus",
    category: "Job Offer",
    subject: "SiBS Employment Offer V2 – Roman Cabanes Lausa – Software Management",
    preview: "Congratulations, Roman! Your approved Employment Offer is ready for review.",
    position: "Software Management – Full Stack",
    account: "CD – Connect",
    status: "clicked",
    senderEmail: "careers@thesiblingssolutions.com",
    replyTo: "recruitment@thesiblingssolutions.com",
    attachments: [
      { name: "SiBS_Offer_Letter_Roman_Lausa_signed.pdf", size: "284 KB" },
      { name: "Benefits_Summary_Handbook_2026.pdf", size: "1.2 MB" },
    ],
    dispatchedBy: "SiBS Talent Acquisition",
    dispatchedAt: "2026-09-14T14:15:22+08:00",
  },
  {
    id: "EML-2026-0914-002",
    recipient: "Mighty Yena Labus",
    email: "mightyyena@gmail.com",
    role: "Candidate",
    site: "Davao City Site",
    category: "Interview",
    subject: "Final Interview Schedule Confirmation – Mighty Yena Labus",
    preview: "Hi Mighty, your final interview with Director Raul Jr. Nadela has been scheduled.",
    position: "Customer Service Representative",
    account: "AHG Inbound/Outbound",
    status: "opened",
    dispatchedBy: "Alena Batacan",
    dispatchedAt: "2026-09-14T13:40:10+08:00",
  },
  {
    id: "EML-2026-0914-003",
    recipient: "Crister Alberca Canitan",
    email: "crister.canitan@thesiblingssolutions.com",
    role: "Approver",
    site: "Tagum City Campus",
    category: "Approval Needed",
    subject: "Action Required: Compensation Offer Review for Carlos Mendoza",
    preview: "Dear VP Crister Canitan, a proposed employment offer is awaiting your review.",
    position: "Technical Support Specialist – Tier 2",
    account: "Atlas Telecom",
    status: "delivered",
    dispatchedBy: "SiBS Approval Bot",
    dispatchedAt: "2026-09-14T11:20:00+08:00",
  },
  {
    id: "EML-2026-0914-004",
    recipient: "Mark Reyes",
    email: "mark.reyes@yahoo.com",
    role: "Candidate",
    site: "Davao City Site",
    category: "Intake Form",
    subject: "SiBS Job Application Link – Customer Service Representative",
    preview: "Thank you for visiting the SiBS Job Fair booth at SM City Davao.",
    position: "Customer Service Representative",
    account: "AHG Inbound/Outbound",
    status: "delivered",
    dispatchedBy: "SiBS Talent Acquisition",
    dispatchedAt: "2026-09-14T10:05:44+08:00",
  },
  {
    id: "EML-2026-0914-005",
    recipient: "Patricia Gomez",
    email: "patricia.gomez@invalid-domain.test",
    role: "Candidate",
    site: "Davao City Site",
    category: "Assessment",
    subject: "Action Required: Complete Your SiBS Typing & Language Assessment",
    preview: "Hi Patricia, thank you for your application. To proceed, please complete the assessment.",
    position: "Customer Service Representative",
    account: "AHG Inbound/Outbound",
    status: "bounced",
    statusDetail: "550 5.1.2 Host or domain name not found",
    dispatchedBy: "SiBS Talent Acquisition",
    dispatchedAt: "2026-09-14T09:12:30+08:00",
  },
  {
    id: "EML-2026-0914-006",
    recipient: "Janica Mae Alcantara",
    email: "janica.alcantara@gmail.com",
    role: "Candidate",
    site: "Davao City Site",
    category: "NHO Schedule",
    subject: "SiBS – New Hire Orientation (NHO) Schedule & Pre-Employment Checklist",
    preview: "Congratulations Janica! Welcome to SiBS. Your New Hire Orientation details are inside.",
    position: "Sales Development Representative",
    account: "Global Cloud Tech",
    status: "clicked",
    dispatchedBy: "SiBS HR Onboarding",
    dispatchedAt: "2026-09-14T08:30:15+08:00",
  },
  {
    id: "EML-2026-0914-007",
    recipient: "Alena Mendoza Batacan",
    email: "alena.batacan@thesiblingssolutions.com",
    role: "Executive",
    site: "All Sites (Tagum & Davao)",
    category: "Weekly Digest",
    subject: "SiBS Talent Acquisition Weekly Summary & Operations Digest",
    preview: "Weekly TA Digest: 48 new applicants sourced, 26 interviews, and 9 offers released.",
    position: "All Active Campaigns",
    account: "Enterprise Overview",
    status: "opened",
    dispatchedBy: "SiBS Analytics System",
    dispatchedAt: "2026-09-14T07:00:02+08:00",
  },
  {
    id: "EML-2026-0913-008",
    recipient: "Joshua Dela Cruz",
    email: "joshua.delacruz@outlook.com",
    role: "Candidate",
    site: "Davao City Site",
    category: "Talent Pool",
    subject: "SiBS Application Status Update – Customer Service Representative",
    preview: "Dear Joshua, thank you for taking the time to speak with our recruitment team.",
    position: "Customer Service Representative",
    account: "AHG Inbound/Outbound",
    status: "opened",
    dispatchedBy: "SiBS Talent Acquisition",
    dispatchedAt: "2026-09-13T16:45:10+08:00",
  },
  {
    id: "EML-2026-0913-009",
    recipient: "Angela Lim",
    email: "angela.lim@gmail.com",
    role: "Candidate",
    site: "Tagum City Campus",
    category: "Interview",
    subject: "Initial Interview Schedule Confirmation – Angela Lim",
    preview: "Your initial interview schedule has been confirmed. Please review the meeting details.",
    position: "Quality Assurance Analyst",
    account: "Nova CX",
    status: "opened",
    dispatchedBy: "Alena Batacan",
    dispatchedAt: "2026-09-13T14:18:55+08:00",
  },
  {
    id: "EML-2026-0913-010",
    recipient: "Jose Mari Santos",
    email: "jose.santos@gmail.com",
    role: "Candidate",
    site: "Tagum City Campus",
    category: "Job Offer",
    subject: "SiBS Employment Offer – Jose Mari Santos – Quality Assurance Analyst",
    preview: "Your approved employment offer is ready for review and electronic acknowledgement.",
    position: "Quality Assurance Analyst",
    account: "Nova CX",
    status: "delivered",
    dispatchedBy: "SiBS Talent Acquisition",
    dispatchedAt: "2026-09-13T12:40:09+08:00",
  },
  {
    id: "EML-2026-0913-011",
    recipient: "Bea Villanueva",
    email: "bea.villanueva@thesiblingssolutions.com",
    role: "Approver",
    site: "Davao City Site",
    category: "Approval Needed",
    subject: "Action Required: Recruitment Offer Approval – Quality Assurance Analyst",
    preview: "A recruitment offer is ready for internal review and approval before candidate dispatch.",
    position: "Quality Assurance Analyst",
    account: "Nova CX",
    status: "delivered",
    dispatchedBy: "SiBS Assessment System",
    dispatchedAt: "2026-09-13T10:22:48+08:00",
  },
  {
    id: "EML-2026-0913-012",
    recipient: "Noel Francisco",
    email: "noel.francisco@example.com",
    role: "Candidate",
    site: "Davao City Site",
    category: "Interview",
    subject: "Updated Interview Schedule – Noel Francisco",
    preview: "Your interview schedule was updated. Open this email to see the latest appointment.",
    position: "Technical Support Specialist",
    account: "Atlas Telecom",
    status: "failed",
    statusDetail: "Relay temporarily unavailable; retry recommended",
    dispatchedBy: "SiBS Talent Acquisition",
    dispatchedAt: "2026-09-13T09:05:33+08:00",
  },
];

export const EMAIL_STATUS_TABS = [
  { value: "all", label: "All Emails" },
  { value: "delivered", label: "Delivered" },
  { value: "opened", label: "Opened" },
  { value: "clicked", label: "Clicked CTA" },
  { value: "bounced", label: "Bounced" },
  { value: "failed", label: "Failed" },
  { value: "internal", label: "Internal Approvals" },
  { value: "relay", label: "Relay Status" },
];
