export const workforceHiringOverviewFilterOptions = {
  weeklyVersions: [
    "2024 - Week 20 | May 13 - May 19, 2024",
    "2024 - Week 21 | May 20 - May 26, 2024",
    "2024 - Week 22 | May 27 - Jun 2, 2024",
  ],
  clusters: ["All Clusters", "Cluster A", "Cluster B"],
  accounts: ["All Accounts", "Account 1", "Account 2", "Account 3", "Account 4"],
};

export const initialWorkforceHiringOverviewFilters = {
  weeklyVersion: workforceHiringOverviewFilterOptions.weeklyVersions[0],
  cluster: workforceHiringOverviewFilterOptions.clusters[0],
  account: workforceHiringOverviewFilterOptions.accounts[0],
};

export const workforceHiringOverviewSummary = {
  requiredHeadcount: 1250,
  actualHeadcount: 1132,
  bufferPercentage: -9.44,
  absenteeism: 62,
  absenteeismPercentage: 5.48,
  attrition: 74,
  attritionPercentage: 6.54,
  netActualHc: 1058,
  hiringNeeded: 192,
  hiringRate: 18.7,
  hiredCount: 88,
  leadsToInterview: 846,
};

export const workforceHiringOverviewPipeline = [
  {
    stage: "Accepted Job Offer",
    short: "Accepted Job Offer",
    count: 158,
    stepConversion: null,
    cumulative: 18.7,
    color: "#1f5a9d",
    text: "text-[#1f5a9d]",
    iconKey: "handshake",
  },
  {
    stage: "NHO",
    short: "NHO Count",
    count: 122,
    stepConversion: 77.22,
    cumulative: 14.4,
    color: "#6c55a3",
    text: "text-[#6c55a3]",
    iconKey: "fileText",
  },
  {
    stage: "FST",
    short: "FST Count",
    count: 98,
    stepConversion: 80.33,
    cumulative: 11.6,
    color: "#0d9298",
    text: "text-[#0d9298]",
    iconKey: "users",
  },
  {
    stage: "PST",
    short: "PST Count",
    count: 74,
    stepConversion: 75.51,
    cumulative: 8.7,
    color: "#f5820b",
    text: "text-[#f5820b]",
    iconKey: "laptop",
  },
  {
    stage: "Go Live",
    short: "Go Live",
    count: 58,
    stepConversion: 78.38,
    cumulative: 6.8,
    color: "#4c9a2a",
    text: "text-[#4c9a2a]",
    iconKey: "rocket",
  },
];

export const workforceHiringOverviewAttritionStages = [
  { fromTo: "Accepted JO -> NHO", count: 36, percentage: 22.78, width: "w-[55%]" },
  { fromTo: "NHO -> FST", count: 24, percentage: 19.67, width: "w-[47%]" },
  { fromTo: "FST -> PST", count: 24, percentage: 24.49, width: "w-[59%]" },
  { fromTo: "NHO -> PST", count: 18, percentage: 14.75, width: "w-[35%]" },
  { fromTo: "PST -> Go Live", count: 16, percentage: 21.62, width: "w-[52%]" },
];

export const workforceHiringOverviewTrendWeeks = [
  "Wk -5",
  "Wk -4",
  "Wk -3",
  "Wk -2",
  "Wk -1",
  "Wk 0",
];

export const workforceHiringOverviewTrends = {
  absenteeism: [5.1, 5.3, 5.0, 5.2, 5.5, 5.5],
  attrition: [5.7, 5.9, 6.1, 6.2, 6.4, 6.5],
  buffer: [-9.8, -9.6, -9.2, -9.1, -9.3, -9.4],
};

export const workforceHiringOverviewDetailRows = [
  {
    cluster: "Cluster A",
    account: "Account 1",
    requiredHeadcount: 250,
    actualHeadcount: 228,
    bufferPercentage: -8.8,
    absenteeism: 12,
    absenteeismPercentage: 4.76,
    attrition: 14,
    attritionPercentage: 5.56,
    netActualHc: 214,
    hiringNeeded: 36,
    acceptedJo: 32,
    nho: 25,
    fst: 20,
    pst: 15,
    goLive: 12,
    joNhoCount: 7,
    joNhoPercentage: 21.88,
    nhoFstCount: 5,
    nhoFstPercentage: 20,
    fstPstCount: 5,
    fstPstPercentage: 25,
    nhoPstCount: 3,
    nhoPstPercentage: 12,
    pstGoLiveCount: 3,
    pstGoLivePercentage: 20,
    hiredCount: 18,
    hiringRate: 20.45,
  },
  {
    cluster: "Cluster A",
    account: "Account 2",
    requiredHeadcount: 300,
    actualHeadcount: 276,
    bufferPercentage: -8,
    absenteeism: 15,
    absenteeismPercentage: 5.43,
    attrition: 18,
    attritionPercentage: 6.52,
    netActualHc: 258,
    hiringNeeded: 42,
    acceptedJo: 38,
    nho: 30,
    fst: 24,
    pst: 18,
    goLive: 14,
    joNhoCount: 8,
    joNhoPercentage: 21.05,
    nhoFstCount: 6,
    nhoFstPercentage: 20,
    fstPstCount: 6,
    fstPstPercentage: 25,
    nhoPstCount: 4,
    nhoPstPercentage: 13.33,
    pstGoLiveCount: 4,
    pstGoLivePercentage: 22.22,
    hiredCount: 20,
    hiringRate: 18.69,
  },
  {
    cluster: "Cluster B",
    account: "Account 3",
    requiredHeadcount: 200,
    actualHeadcount: 186,
    bufferPercentage: -7,
    absenteeism: 8,
    absenteeismPercentage: 4.3,
    attrition: 10,
    attritionPercentage: 5.38,
    netActualHc: 176,
    hiringNeeded: 24,
    acceptedJo: 26,
    nho: 20,
    fst: 16,
    pst: 12,
    goLive: 9,
    joNhoCount: 6,
    joNhoPercentage: 23.08,
    nhoFstCount: 4,
    nhoFstPercentage: 20,
    fstPstCount: 4,
    fstPstPercentage: 25,
    nhoPstCount: 2,
    nhoPstPercentage: 10,
    pstGoLiveCount: 3,
    pstGoLivePercentage: 25,
    hiredCount: 12,
    hiringRate: 18.18,
  },
  {
    cluster: "Cluster B",
    account: "Account 4",
    requiredHeadcount: 180,
    actualHeadcount: 168,
    bufferPercentage: -6.67,
    absenteeism: 7,
    absenteeismPercentage: 4.17,
    attrition: 8,
    attritionPercentage: 4.76,
    netActualHc: 160,
    hiringNeeded: 22,
    acceptedJo: 16,
    nho: 12,
    fst: 12,
    pst: 9,
    goLive: 7,
    joNhoCount: 6,
    joNhoPercentage: 27.27,
    nhoFstCount: 4,
    nhoFstPercentage: 25,
    fstPstCount: 3,
    fstPstPercentage: 25,
    nhoPstCount: 2,
    nhoPstPercentage: 12.5,
    pstGoLiveCount: 2,
    pstGoLivePercentage: 22.22,
    hiredCount: 10,
    hiringRate: 20,
  },
];
