export const CANDIDATE_APPLICATIONS_STORAGE_KEY = "ta_candidate_applications";
export const PIPELINE_CANDIDATES_STORAGE_KEY = "ta_pipeline_candidates";
export const OFFER_ELIGIBLE_STORAGE_KEY = "ta_offer_eligible_candidates";
export const OFFER_RECORDS_STORAGE_KEY = "ta_offer_records";
export const INTERNAL_CANDIDATES_STORAGE_KEY = "ta_internal_candidates";
export const PUBLIC_SUBMISSIONS_KEY = "ta_public_candidate_submissions";
export const PIPELINE_SYNC_EVENTS_KEY = "ta_pipeline_sync_events";

export const pipelineStages = [
  "Initial Screening",
  "Online Assessment",
  "Interview Scheduled",
  "Interviewed",
  "Offered",
  "Accepted (For NHO)",
  "Incomplete Requirements",
  "Drop-off",
];

export const normalStageFlow = [
  "Initial Screening",
  "Online Assessment",
  "Interview Scheduled",
  "Interviewed",
  "Offered",
  "Accepted",
];

export const roleOptions = [
  "All Roles",
  "Not assigned yet",
  "Customer Service Representative",
  "QA Specialist",
  "RCM Analyst",
  "IT Support",
  "HR Assistant",
  "System Developer",
  "Accounting Staff",
];

export const accountOptions = [
  "All Accounts",
  "Not assigned yet",
  "Collect IV",
  "Collect AR",
  "Connect",
  "DentistRX",
  "Reconciliation",
  "TeleDentistry",
  "Cash",
  "US Visa",
  "Channel Assist",
  "Yomdel",
];

export const hiringRequirementOptions = [
  {
    id: "HIR-001",
    label: "HIR-001 — Customer Service Representative / Collect IV",
    roleTitle: "Customer Service Representative",
    account: "Collect IV",
  },
  {
    id: "HIR-002",
    label: "HIR-002 — QA Specialist / Connect",
    roleTitle: "QA Specialist",
    account: "Connect",
  },
  {
    id: "HIR-003",
    label: "HIR-003 — RCM Analyst / Reconciliation",
    roleTitle: "RCM Analyst",
    account: "Reconciliation",
  },
  {
    id: "HIR-004",
    label: "HIR-004 — IT Support / SIBS",
    roleTitle: "IT Support",
    account: "SIBS",
  },
  {
    id: "HIR-005",
    label: "HIR-005 — Customer Service Representative / US Visa",
    roleTitle: "Customer Service Representative",
    account: "US Visa",
  },
];

export const interviewTypeOptions = ["Online", "Face-to-face"];

export const offerApprovers = ["Raul Nadela", "Haasanor"];

export const offerApprovalStatusOptions = [
  "For Review",
  "Approved",
  "Rejected",
];

export const offerDecisionOptions = ["Negotiate", "Rejected", "Accepted"];

export const prfStatusOptions = ["Review", "Matched", "Unmatched"];

export const assessmentStatusOptions = ["Not Take", "Taken"];

export const assessmentResultOptions = ["Assessment Fit", "Assessment Not Fit"];

export const dropOffCategoryOptions = [
  "No Show",
  "Compensation",
  "Schedule",
  "Process Delay",
  "No Response",
  "Failed Assessment",
  "Failed Interview",
  "Accepted Other Offer",
  "Location Issue",
  "Personal Reason",
  "Incomplete Requirements",
  "Others",
];

export const defaultPipelineCandidates = [
  {
    id: 1,
    candidateApplicationId: "APP-001",
    applicationId: "APP-001",
    candidateMasterId: 1,
    candidateId: "CAND-001",
    name: "Juan Santos Dela Cruz",
    candidateName: "Juan Santos Dela Cruz",
    email: "juan.delacruz@email.com",
    contactNumber: "09123456789",
    roleTitle: "Not assigned yet",
    account: "Not assigned yet",
    roleAccount: "Not assigned yet - Not assigned yet",
    source: "Employee Referral Program",
    owner: "Maria Reyes",
    taOwner: "Maria Reyes",
    currentStage: "Initial Screening",
    previousStage: null,
    applicationStatus: "Active",
    prfStatus: "Review",
    prfReviewed: false,
    prfReviewedAt: null,
    interviewDate: null,
    interviewType: "-",
    interviewStatus: "For Assessment",
    assessmentStatus: "Not Take",
    assessmentResult: "",
    assessmentEmailSent: false,
    assessmentEmailSentAt: null,
    assessmentTakenAt: null,
    assessmentTaggedAt: null,
    assessmentRemarks: "",
    dateMoved: "2026-05-02",
    updatedAt: "2026-05-02",
    reasonForMovement:
      "Candidate moved from Talent Pool without final role, account, or hiring requirement assignment.",
    avatarColor: "bg-blue-600",
    dropOffReason: null,
    dropOffCategory: null,
    dropOffRemarks: null,
    candidateSnapshot: {
      id: 1,
      candidateId: "CAND-001",
      name: "Juan Santos Dela Cruz",
      firstName: "Juan",
      middleName: "Santos",
      lastName: "Dela Cruz",
      email: "juan.delacruz@email.com",
      phoneNumber1: "09123456789",
      openPosition: "Customer Service Representative",
      applyingLocation: "Davao Site",
      source: "Employee Referral Program",
      skillsLanguage: "English, Chat Support, Customer Service",
    },
    timeline: [
      {
        stage: "Initial Screening",
        owner: "Maria Reyes",
        source: "Talent Pool",
        timestamp: "May 2, 2026, 9:00 AM",
        reason:
          "Candidate moved from Talent Pool. Final role/account assignment is pending until Offered stage.",
      },
    ],
  },
  {
    id: 2,
    candidateApplicationId: "APP-002",
    applicationId: "APP-002",
    candidateMasterId: 2,
    candidateId: "CAND-002",
    name: "Maria Lopez Santos",
    candidateName: "Maria Lopez Santos",
    email: "maria.santos@email.com",
    contactNumber: "09171234567",
    roleTitle: "Not assigned yet",
    account: "Not assigned yet",
    roleAccount: "Not assigned yet - Not assigned yet",
    source: "Social Media Ads",
    owner: "John Dela Cruz",
    taOwner: "John Dela Cruz",
    currentStage: "Initial Screening",
    previousStage: "Initial Screening",
    applicationStatus: "Active",
    prfStatus: "Matched",
    prfReviewed: true,
    prfReviewedAt: "May 4, 2026, 10:30 AM",
    interviewDate: null,
    interviewType: "-",
    interviewStatus: "For Assessment",
    assessmentStatus: "Not Take",
    assessmentResult: "",
    assessmentEmailSent: false,
    assessmentEmailSentAt: null,
    assessmentTakenAt: null,
    assessmentTaggedAt: null,
    assessmentRemarks: "",
    dateMoved: "2026-05-04",
    updatedAt: "2026-05-04",
    reasonForMovement:
      "PRF status changed to Matched. Candidate moved from Initial Screening to Initial Screening.",
    avatarColor: "bg-cyan-600",
    dropOffReason: null,
    dropOffCategory: null,
    dropOffRemarks: null,
    candidateSnapshot: {
      id: 2,
      candidateId: "CAND-002",
      name: "Maria Lopez Santos",
      firstName: "Maria",
      middleName: "Lopez",
      lastName: "Santos",
      email: "maria.santos@email.com",
      phoneNumber1: "09171234567",
      openPosition: "QA Specialist",
      applyingLocation: "Davao Site",
      source: "Social Media Ads",
      skillsLanguage: "QA, English, Documentation",
    },
    timeline: [
      {
        stage: "Initial Screening",
        owner: "John Dela Cruz",
        source: "Talent Pool",
        timestamp: "May 4, 2026, 9:15 AM",
        reason: "Candidate moved from Talent Pool without final assignment.",
      },
      {
        stage: "Initial Screening",
        owner: "John Dela Cruz",
        source: "PRF Review",
        timestamp: "May 4, 2026, 10:30 AM",
        reason:
          "PRF status changed to Matched. Candidate moved to Initial Screening.",
        remarks: "PRF Status: Matched",
      },
    ],
  },
  {
    id: 3,
    candidateApplicationId: "APP-003",
    applicationId: "APP-003",
    candidateMasterId: 3,
    candidateId: "CAND-003",
    name: "Mark Villanueva Reyes",
    candidateName: "Mark Villanueva Reyes",
    email: "mark.reyes@email.com",
    contactNumber: "09281234567",
    roleTitle: "Not assigned yet",
    account: "Not assigned yet",
    roleAccount: "Not assigned yet - Not assigned yet",
    source: "Online Job Portals",
    owner: "Kim Domingo",
    taOwner: "Kim Domingo",
    currentStage: "Online Assessment",
    previousStage: "Initial Screening",
    applicationStatus: "Active",
    prfStatus: "Matched",
    prfReviewed: true,
    prfReviewedAt: "May 6, 2026, 11:00 AM",
    interviewDate: null,
    interviewType: "-",
    interviewStatus: "For Assessment",
    assessmentStatus: "Taken",
    assessmentResult: "Assessment Fit",
    assessmentEmailSent: true,
    assessmentEmailSentAt: "May 6, 2026, 11:15 AM",
    assessmentTakenAt: "May 6, 2026, 3:00 PM",
    assessmentTaggedAt: "May 6, 2026, 4:00 PM",
    assessmentRemarks:
      "Candidate passed online assessment and is ready for interview scheduling.",
    dateMoved: "2026-05-06",
    updatedAt: "2026-05-06",
    reasonForMovement:
      "Assessment marked as Taken and tagged as Assessment Fit.",
    avatarColor: "bg-orange-600",
    dropOffReason: null,
    dropOffCategory: null,
    dropOffRemarks: null,
    candidateSnapshot: {
      id: 3,
      candidateId: "CAND-003",
      name: "Mark Villanueva Reyes",
      firstName: "Mark",
      middleName: "Villanueva",
      lastName: "Reyes",
      email: "mark.reyes@email.com",
      phoneNumber1: "09281234567",
      openPosition: "RCM Analyst",
      applyingLocation: "Tagum Site",
      source: "Online Job Portals",
      skillsLanguage: "RCM, Healthcare, Documentation",
    },
    timeline: [
      {
        stage: "Initial Screening",
        owner: "Kim Domingo",
        source: "Talent Pool",
        timestamp: "May 6, 2026, 9:00 AM",
        reason: "Candidate moved from Talent Pool without final assignment.",
      },
      {
        stage: "Initial Screening",
        owner: "Kim Domingo",
        source: "PRF Review",
        timestamp: "May 6, 2026, 11:00 AM",
        reason:
          "PRF status changed to Matched. Candidate moved to Initial Screening.",
      },
      {
        stage: "Online Assessment",
        owner: "Kim Domingo",
        source: "Online Assessment",
        timestamp: "May 6, 2026, 11:15 AM",
        reason: "Candidate moved to Online Assessment. Assessment email sent.",
      },
      {
        stage: "Online Assessment",
        owner: "Kim Domingo",
        source: "Online Assessment",
        timestamp: "May 6, 2026, 4:00 PM",
        reason: "Assessment marked as Taken and tagged as Assessment Fit.",
      },
    ],
  },
  {
    id: 4,
    candidateApplicationId: "APP-004",
    applicationId: "APP-004",
    candidateMasterId: 4,
    candidateId: "CAND-004",
    name: "Ana Garcia Lim",
    candidateName: "Ana Garcia Lim",
    email: "ana.lim@email.com",
    contactNumber: "09351234567",
    roleTitle: "IT Support",
    account: "SIBS IT",
    roleAccount: "IT Support - SIBS IT",
    source: "Walk In",
    owner: "Paul Garcia",
    taOwner: "Paul Garcia",
    currentStage: "Offered",
    previousStage: "Interviewed",
    applicationStatus: "Active",
    prfStatus: "Matched",
    prfReviewed: true,
    prfReviewedAt: "May 8, 2026, 9:30 AM",
    interviewDate: "2026-05-10T10:30",
    interviewType: "Face-to-face",
    interviewStatus: "Completed",
    assessmentStatus: "Taken",
    assessmentResult: "Assessment Fit",
    assessmentEmailSent: true,
    assessmentEmailSentAt: "May 8, 2026, 10:00 AM",
    assessmentTakenAt: "May 8, 2026, 2:30 PM",
    assessmentTaggedAt: "May 8, 2026, 3:00 PM",
    assessmentRemarks: "Candidate passed the online assessment.",
    dateMoved: "2026-05-10",
    updatedAt: "2026-05-10",
    reasonForMovement:
      "Offer details prepared. Final role and account were assigned during Offered stage.",
    avatarColor: "bg-violet-600",
    offerDetails: {
      roleTitle: "IT Support",
      account: "SIBS IT",
      compensation: 27000,
      basicPay: 24000,
      deminimisDailyRate: 3000,
      preparedAt: "May 10, 2026, 4:00 PM",
      preparedBy: "Paul Garcia",
    },
    offerApprovals: {
      "Raul Nadela": { status: "For Review", updatedAt: null, remarks: "" },
      Haasanor: { status: "For Review", updatedAt: null, remarks: "" },
    },
    offerApprovalStatus: "For Review",
    offerEmailSent: false,
    offerEmailSentAt: null,
    offerDecision: "",
    offerDecisionAt: null,
    offerDecisionRemarks: "",
    dropOffReason: null,
    dropOffCategory: null,
    dropOffRemarks: null,
    candidateSnapshot: {
      id: 4,
      candidateId: "CAND-004",
      name: "Ana Garcia Lim",
      firstName: "Ana",
      middleName: "Garcia",
      lastName: "Lim",
      email: "ana.lim@email.com",
      phoneNumber1: "09351234567",
      openPosition: "IT Support",
      applyingLocation: "Mabini Site",
      source: "Walk In",
      skillsLanguage: "Tech, Troubleshooting, English",
    },
    timeline: [
      {
        stage: "Initial Screening",
        owner: "Paul Garcia",
        source: "Talent Pool",
        timestamp: "May 8, 2026, 8:45 AM",
        reason:
          "Candidate moved from Talent Pool without final role or account assignment.",
      },
      {
        stage: "Initial Screening",
        owner: "Paul Garcia",
        source: "PRF Review",
        timestamp: "May 8, 2026, 9:30 AM",
        reason:
          "PRF status changed to Matched. Candidate moved to Initial Screening.",
      },
      {
        stage: "Online Assessment",
        owner: "Paul Garcia",
        source: "Online Assessment",
        timestamp: "May 8, 2026, 10:00 AM",
        reason:
          "Candidate moved to Online Assessment and assessment email was sent.",
      },
      {
        stage: "Online Assessment",
        owner: "Paul Garcia",
        source: "Online Assessment",
        timestamp: "May 8, 2026, 3:00 PM",
        reason: "Assessment marked as Taken and tagged as Assessment Fit.",
      },
      {
        stage: "Interview Scheduled",
        owner: "Paul Garcia",
        source: "Interview Scheduling",
        timestamp: "May 9, 2026, 2:00 PM",
        reason: "Candidate passed assessment and interview schedule was set.",
      },
      {
        stage: "Interviewed",
        owner: "Paul Garcia",
        source: "Interview",
        timestamp: "May 10, 2026, 11:30 AM",
        reason: "Interview completed. Candidate moved to Interviewed.",
      },
      {
        stage: "Offered",
        owner: "Paul Garcia",
        source: "Offer Approval",
        timestamp: "May 10, 2026, 4:00 PM",
        reason: "Final role and account assigned during Offered stage.",
        remarks:
          "Offer Role: IT Support, Offer Account: SIBS IT, Compensation: ₱27,000",
      },
    ],
  },
  {
    id: 5,
    candidateApplicationId: "APP-005",
    applicationId: "APP-005",
    candidateMasterId: 5,
    candidateId: "CAND-005",
    name: "Leonardo Ramos Cruz",
    candidateName: "Leonardo Ramos Cruz",
    email: "leo.cruz@email.com",
    contactNumber: "09451234567",
    roleTitle: "Not assigned yet",
    account: "Not assigned yet",
    roleAccount: "Not assigned yet - Not assigned yet",
    source: "Institutional Partnership",
    owner: "Maria Reyes",
    taOwner: "Maria Reyes",
    currentStage: "Drop-off",
    previousStage: "Initial Screening",
    applicationStatus: "Closed",
    prfStatus: "Matched",
    prfReviewed: true,
    prfReviewedAt: "May 12, 2026, 10:00 AM",
    interviewDate: null,
    interviewType: "-",
    interviewStatus: "For Assessment",
    assessmentStatus: "Not Take",
    assessmentResult: "",
    assessmentEmailSent: false,
    assessmentEmailSentAt: null,
    assessmentTakenAt: null,
    assessmentTaggedAt: null,
    assessmentRemarks: "",
    dateMoved: "2026-05-13",
    updatedAt: "2026-05-13",
    reasonForMovement:
      "Candidate moved from Initial Screening to Drop-off. Reason: No response after follow-up calls and messages.",
    avatarColor: "bg-red-600",
    offerDetails: null,
    offerApprovals: {
      "Raul Nadela": { status: "For Review", updatedAt: null, remarks: "" },
      Haasanor: { status: "For Review", updatedAt: null, remarks: "" },
    },
    offerApprovalStatus: "For Review",
    offerEmailSent: false,
    offerEmailSentAt: null,
    offerDecision: "",
    offerDecisionAt: null,
    offerDecisionRemarks: "",
    dropOffReason: "No response after follow-up calls and messages.",
    dropOffCategory: "No Response",
    dropOffRemarks:
      "TA attempted to reach candidate on May 12 and May 13, but candidate did not respond.",
    candidateSnapshot: {
      id: 5,
      candidateId: "CAND-005",
      name: "Leonardo Ramos Cruz",
      firstName: "Leonardo",
      middleName: "Ramos",
      lastName: "Cruz",
      email: "leo.cruz@email.com",
      phoneNumber1: "09451234567",
      openPosition: "Accounting Staff",
      applyingLocation: "Davao Site",
      source: "Institutional Partnership",
      skillsLanguage: "Accounting, Documentation, Excel",
    },
    timeline: [
      {
        stage: "Initial Screening",
        owner: "Maria Reyes",
        source: "Talent Pool",
        timestamp: "May 12, 2026, 8:30 AM",
        reason:
          "Candidate moved from Talent Pool without final role or account assignment.",
      },
      {
        stage: "Initial Screening",
        owner: "Maria Reyes",
        source: "PRF Review",
        timestamp: "May 12, 2026, 10:00 AM",
        reason:
          "PRF status changed to Matched. Candidate moved to Initial Screening.",
      },
      {
        stage: "Drop-off",
        owner: "Maria Reyes",
        source: "Candidate Follow-up",
        timestamp: "May 13, 2026, 4:30 PM",
        reason:
          "Candidate moved from Initial Screening to Drop-off. Reason: No response after follow-up calls and messages.",
        dropOffCategory: "No Response",
        dropOffReason: "No response after follow-up calls and messages.",
        remarks:
          "TA attempted to reach candidate on May 12 and May 13, but candidate did not respond.",
      },
    ],
  },
];
