export const STATIC_PIPELINE_CANDIDATES = [
  {
    id: "pipe-cand-001",
    candidateId: "CAND-2026-001",
    candidateApplicationId: "APP-2026-001",
    name: "Juan Carlos Dela Cruz",
    candidateName: "Juan Carlos Dela Cruz",
    email: "juancarlos.delacruz@example.com",
    phone: "+63 917 123 4567",
    roleTitle: "Full Stack Developer",
    account: "Software Management",
    roleAccount: "Full Stack Developer - Software Management",
    department: "IT (Information and Communications Technology)",
    currentStage: "Initial Screening",
    currentPipelineStage: "Initial Screening",
    pipelineStage: "Initial Screening",
    stage: "Initial Screening",
    rating: 4.5,
    matchScore: 92,
    prfStatus: "Matched",
    prfReviewed: true,
    assessmentStatus: "Not Take",
    assessmentResult: "",
    interviewDate: null,
    interviewType: null,
    interviewStatus: "For Scheduling",
    appliedDate: "2026-08-14",
    timeline: [
      {
        stage: "Initial Screening",
        date: "2026-08-14",
        action: "Profile Created",
        remarks: "Resume screened and shortlisted for technical review.",
      },
    ],
  },
  {
    id: "pipe-cand-002",
    candidateId: "CAND-2026-002",
    candidateApplicationId: "APP-2026-002",
    name: "Maria Santos",
    candidateName: "Maria Santos",
    email: "maria.santos@example.com",
    phone: "+63 918 234 5678",
    roleTitle: "Customer Support Specialist",
    account: "US Visa",
    roleAccount: "Customer Support Specialist - US Visa",
    department: "Operations",
    currentStage: "Initial Screening",
    currentPipelineStage: "Initial Screening",
    pipelineStage: "Initial Screening",
    stage: "Initial Screening",
    rating: 4.2,
    matchScore: 88,
    prfStatus: "Review",
    prfReviewed: false,
    assessmentStatus: "Not Take",
    assessmentResult: "",
    interviewDate: null,
    interviewType: null,
    interviewStatus: "For Scheduling",
    appliedDate: "2026-08-15",
    timeline: [
      {
        stage: "Initial Screening",
        date: "2026-08-15",
        action: "Application Received",
        remarks: "Candidate applied via Careers Portal.",
      },
    ],
  },
  {
    id: "pipe-cand-003",
    candidateId: "CAND-2026-003",
    candidateApplicationId: "APP-2026-003",
    name: "Angelica Ramos",
    candidateName: "Angelica Ramos",
    email: "angelica.ramos@example.com",
    phone: "+63 919 345 6789",
    roleTitle: "QA Automation Engineer",
    account: "Software Management",
    roleAccount: "QA Automation Engineer - Software Management",
    department: "IT (Information and Communications Technology)",
    currentStage: "Online Assessment",
    currentPipelineStage: "Online Assessment",
    pipelineStage: "Online Assessment",
    stage: "Online Assessment",
    rating: 4.8,
    matchScore: 95,
    prfStatus: "Matched",
    prfReviewed: true,
    assessmentStatus: "Taken",
    assessmentResult: "Assessment Fit",
    interviewDate: null,
    interviewType: null,
    interviewStatus: "For Scheduling",
    appliedDate: "2026-08-10",
    timeline: [
      {
        stage: "Initial Screening",
        date: "2026-08-10",
        action: "Screening Passed",
        remarks: "High match score on test automation frameworks.",
      },
      {
        stage: "Online Assessment",
        date: "2026-08-12",
        action: "Assessment Link Sent",
        remarks: "Online assessment invitation triggered.",
      },
    ],
  },
  {
    id: "pipe-cand-004",
    candidateId: "CAND-2026-004",
    candidateApplicationId: "APP-2026-004",
    name: "Kevin Joshua Tan",
    candidateName: "Kevin Joshua Tan",
    email: "kevin.tan@example.com",
    phone: "+63 920 456 7890",
    roleTitle: "Frontend Developer",
    account: "Software Management",
    roleAccount: "Frontend Developer - Software Management",
    department: "IT (Information and Communications Technology)",
    currentStage: "Online Assessment",
    currentPipelineStage: "Online Assessment",
    pipelineStage: "Online Assessment",
    stage: "Online Assessment",
    rating: 4.0,
    matchScore: 85,
    prfStatus: "Review",
    prfReviewed: false,
    assessmentStatus: "Not Take",
    assessmentResult: "",
    interviewDate: null,
    interviewType: null,
    interviewStatus: "For Scheduling",
    appliedDate: "2026-08-13",
    timeline: [
      {
        stage: "Initial Screening",
        date: "2026-08-13",
        action: "Screening Passed",
        remarks: "React / Tailwind portfolio validated.",
      },
    ],
  },
  {
    id: "pipe-cand-005",
    candidateId: "CAND-2026-005",
    candidateApplicationId: "APP-2026-005",
    name: "Patricia Nicole Lopez",
    candidateName: "Patricia Nicole Lopez",
    email: "patricia.lopez@example.com",
    phone: "+63 921 567 8901",
    roleTitle: "Business Analyst",
    account: "Operations",
    roleAccount: "Business Analyst - Operations",
    department: "Operations",
    currentStage: "Assessment Fit",
    currentPipelineStage: "Assessment Fit",
    pipelineStage: "Assessment Fit",
    stage: "Assessment Fit",
    rating: 4.6,
    matchScore: 90,
    prfStatus: "Matched",
    prfReviewed: true,
    assessmentStatus: "Taken",
    assessmentResult: "Assessment Fit",
    interviewDate: null,
    interviewType: null,
    interviewStatus: "For Scheduling",
    appliedDate: "2026-08-08",
    timeline: [
      {
        stage: "Online Assessment",
        date: "2026-08-11",
        action: "Assessment Completed",
        remarks: "Scored 94% on analytical reasoning and documentation.",
      },
    ],
  },
  {
    id: "pipe-cand-006",
    candidateId: "CAND-2026-006",
    candidateApplicationId: "APP-2026-006",
    name: "Rochelle Mae Bautista",
    candidateName: "Rochelle Mae Bautista",
    email: "rochelle.bautista@example.com",
    phone: "+63 922 678 9012",
    roleTitle: "Full Stack Developer",
    account: "Software Management",
    roleAccount: "Full Stack Developer - Software Management",
    department: "IT (Information and Communications Technology)",
    currentStage: "Interview Scheduled",
    currentPipelineStage: "Interview Scheduled",
    pipelineStage: "Interview Scheduled",
    stage: "Interview Scheduled",
    rating: 4.9,
    matchScore: 96,
    prfStatus: "Matched",
    prfReviewed: true,
    assessmentStatus: "Taken",
    assessmentResult: "Assessment Fit",
    interviewDate: "2026-08-20 14:00",
    interviewType: "Online",
    onlineInterviewLink: "https://meet.google.com/abc-defg-hij",
    interviewStatus: "Scheduled",
    appliedDate: "2026-08-05",
    timeline: [
      {
        stage: "Interview Scheduled",
        date: "2026-08-16",
        action: "Interview Booked",
        remarks: "Technical Panel interview set for August 20, 2:00 PM.",
      },
    ],
  },
  {
    id: "pipe-cand-007",
    candidateId: "CAND-2026-007",
    candidateApplicationId: "APP-2026-007",
    name: "Joshua Gabriel Lim",
    candidateName: "Joshua Gabriel Lim",
    email: "joshua.lim@example.com",
    phone: "+63 923 789 0123",
    roleTitle: "HR Specialist",
    account: "Human Resources",
    roleAccount: "HR Specialist - Human Resources",
    department: "Human Resources",
    currentStage: "Interview Scheduled",
    currentPipelineStage: "Interview Scheduled",
    pipelineStage: "Interview Scheduled",
    stage: "Interview Scheduled",
    rating: 4.3,
    matchScore: 89,
    prfStatus: "Matched",
    prfReviewed: true,
    assessmentStatus: "Taken",
    assessmentResult: "Assessment Fit",
    interviewDate: "2026-08-21 10:30",
    interviewType: "Online",
    onlineInterviewLink: "https://meet.google.com/xyz-uvwx-rst",
    interviewStatus: "Scheduled",
    appliedDate: "2026-08-06",
    timeline: [
      {
        stage: "Interview Scheduled",
        date: "2026-08-17",
        action: "Interview Booked",
        remarks: "Managerial interview scheduled.",
      },
    ],
  },
  {
    id: "pipe-cand-008",
    candidateId: "CAND-2026-008",
    candidateApplicationId: "APP-2026-008",
    name: "Bea Alonzo Ramos",
    candidateName: "Bea Alonzo Ramos",
    email: "bea.ramos@example.com",
    phone: "+63 924 890 1234",
    roleTitle: "FST Trainer",
    account: "Training Management",
    roleAccount: "FST Trainer - Training Management",
    department: "Training",
    currentStage: "Interviewed",
    currentPipelineStage: "Interviewed",
    pipelineStage: "Interviewed",
    stage: "Interviewed",
    rating: 4.7,
    matchScore: 93,
    prfStatus: "Matched",
    prfReviewed: true,
    assessmentStatus: "Taken",
    assessmentResult: "Assessment Fit",
    interviewDate: "2026-08-18 11:00",
    interviewType: "Face-to-face",
    interviewStatus: "Completed",
    appliedDate: "2026-08-01",
    timeline: [
      {
        stage: "Interviewed",
        date: "2026-08-18",
        action: "Interview Completed",
        remarks: "Candidate demonstrated strong communication & training acumen.",
      },
    ],
  },
  {
    id: "pipe-cand-009",
    candidateId: "CAND-2026-009",
    candidateApplicationId: "APP-2026-009",
    name: "Samantha Nicole Garcia",
    candidateName: "Samantha Nicole Garcia",
    email: "samantha.garcia@example.com",
    phone: "+63 925 901 2345",
    roleTitle: "Senior React Engineer",
    account: "Software Management",
    roleAccount: "Senior React Engineer - Software Management",
    department: "IT (Information and Communications Technology)",
    currentStage: "Offered",
    currentPipelineStage: "Offered",
    pipelineStage: "Offered",
    stage: "Offered",
    rating: 5.0,
    matchScore: 98,
    prfStatus: "Matched",
    prfReviewed: true,
    assessmentStatus: "Taken",
    assessmentResult: "Assessment Fit",
    basicPay: 48000,
    deminimisDailyRate: 250,
    offerApprovals: {
      "Raul Nadela": { status: "Approved", date: "2026-08-18" },
      Haasanor: { status: "Approved", date: "2026-08-18" },
    },
    offerStatus: "Approved",
    appliedDate: "2026-07-28",
    timeline: [
      {
        stage: "Offered",
        date: "2026-08-18",
        action: "Offer Approved",
        remarks: "Offer letter generated and approved by management.",
      },
    ],
  },
  {
    id: "pipe-cand-010",
    candidateId: "CAND-2026-010",
    candidateApplicationId: "APP-2026-010",
    name: "Catherine Joy Perez",
    candidateName: "Catherine Joy Perez",
    email: "catherine.perez@example.com",
    phone: "+63 926 012 3456",
    roleTitle: "Full Stack Developer",
    account: "Software Management",
    roleAccount: "Full Stack Developer - Software Management",
    department: "IT (Information and Communications Technology)",
    currentStage: "Accepted",
    currentPipelineStage: "Accepted",
    pipelineStage: "Accepted",
    stage: "Accepted",
    rating: 4.9,
    matchScore: 97,
    prfStatus: "Matched",
    prfReviewed: true,
    assessmentStatus: "Taken",
    assessmentResult: "Assessment Fit",
    basicPay: 45000,
    deminimisDailyRate: 200,
    startDate: "2026-09-01",
    offerStatus: "Accepted",
    appliedDate: "2026-07-25",
    timeline: [
      {
        stage: "Accepted",
        date: "2026-08-17",
        action: "Offer Accepted",
        remarks: "Candidate signed employment contract. Start date: Sep 1, 2026.",
      },
    ],
  },
  {
    id: "pipe-cand-011",
    candidateId: "CAND-2026-011",
    candidateApplicationId: "APP-2026-011",
    name: "Jerome Michael Fernandez",
    candidateName: "Jerome Michael Fernandez",
    email: "jerome.fernandez@example.com",
    phone: "+63 927 123 7890",
    roleTitle: "Technical Support Specialist",
    account: "IT Infrastructure",
    roleAccount: "Technical Support Specialist - IT Infrastructure",
    department: "IT (Information and Communications Technology)",
    currentStage: "For NHO",
    currentPipelineStage: "For NHO",
    pipelineStage: "For NHO",
    stage: "For NHO",
    rating: 4.6,
    matchScore: 91,
    prfStatus: "Matched",
    prfReviewed: true,
    assessmentStatus: "Taken",
    assessmentResult: "Assessment Fit",
    nhoDate: "2026-09-01",
    appliedDate: "2026-07-20",
    timeline: [
      {
        stage: "For NHO",
        date: "2026-08-16",
        action: "Scheduled for Orientation",
        remarks: "NHO packet dispatched and pre-employment medical cleared.",
      },
    ],
  },
];
